const https = require('https');
const fs = require('fs');

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const PR_TITLE = process.env.PR_TITLE || 'Pull Request';
const PR_AUTHOR = process.env.PR_AUTHOR || 'unknown';

// Read the diff, files, and commits
const diff = fs.readFileSync('/tmp/pr-diff.txt', 'utf8');
const changedFiles = fs.readFileSync('/tmp/changed-files.txt', 'utf8');
const commits = fs.readFileSync('/tmp/pr-commits.txt', 'utf8');

const prompt = `You are an expert code reviewer. Please review the following pull request thoroughly.

PR Title: ${PR_TITLE}
Author: @${PR_AUTHOR}

Changed Files:
${changedFiles}

Commits:
${commits}

Code Changes:
${diff}

Please provide a comprehensive code review covering:

1. **Code Quality**: Assess readability, maintainability, and adherence to best practices
2. **Potential Bugs**: Identify any logical errors, edge cases, or potential runtime issues
3. **Security Concerns**: Flag any security vulnerabilities (SQL injection, XSS, authentication issues, etc.)
4. **Performance**: Note any performance concerns or optimization opportunities
5. **Testing**: Comment on test coverage and quality
6. **Suggestions**: Provide specific, actionable improvement suggestions

Format your review in markdown with clear sections. Be constructive and specific. If the code looks good, say so! Focus on important issues rather than minor style preferences.

For critical issues, use ⚠️
For suggestions, use 💡
For positive feedback, use ✅`;

const requestBody = JSON.stringify({
  model: 'claude-sonnet-4-5-20250929',
  max_tokens: 4000,
  messages: [
    {
      role: 'user',
      content: prompt
    }
  ]
});

const options = {
  hostname: 'api.anthropic.com',
  path: '/v1/messages',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'x-api-key': ANTHROPIC_API_KEY,
    'anthropic-version': '2023-06-01',
    'Content-Length': Buffer.byteLength(requestBody)
  }
};

const req = https.request(options, (res) => {
  let data = '';

  res.on('data', (chunk) => {
    data += chunk;
  });

  res.on('end', () => {
    try {
      const response = JSON.parse(data);

      if (response.content && response.content[0] && response.content[0].text) {
        const review = response.content[0].text;

        // Add header and footer
        const fullReview = `## 🤖 Automated Code Review

${review}

---
*Review generated by [Claude](https://claude.ai) • If you have questions about this review, feel free to ask!*`;

        // Write to file for the next step
        fs.writeFileSync('/tmp/code-review.txt', fullReview);
        console.log('✅ Successfully generated code review');
      } else {
        console.error('❌ Unexpected API response format:', response);
        process.exit(1);
      }
    } catch (error) {
      console.error('❌ Error parsing response:', error);
      console.error('Raw response:', data);
      process.exit(1);
    }
  });
});

req.on('error', (error) => {
  console.error('❌ Request error:', error);
  process.exit(1);
});

req.write(requestBody);
req.end();
